---
kind: pipeline
name: default

branches:
  - master
  - develop

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7.3.0-cli-alpine3.8
  commands:
    - vendor/bin/phpunit

- name: notification
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: notifications
