<?php
/**
* Nevnapok - PHP Hungarian Namedays.
*
* This program can be used to query the Hungarian name days.
* Works well with leap years.
* 
* The current nameday can be queried with these codes:
* $nevnap = new Nevnap();
* $nevnap->getNamedays();
*
* @author Tamás András Horváth <htomy92@gmail.com>
* @license The MIT License (MIT)
* @link http://icetee.hu
* @version 2014 Stable
* @since version 1.1.2
*/

class NevnapLista extends Nevnap  {

	/*
	*
	* @function data storage
	* @return name day array
	* Language: hu_HU, pl_PL
	*
	*/
	public function nevNapok($lang) {

		switch ($lang) {
			case "hu_HU":
				return array(
					1		=>	array(
						array("Alpár", "Fruzsina", "Bazil"),
						array("Ábel", "Gergely", "Vazul"),
						array("Genovéva", "Gyöngyvér", "Benjámin", "Dzsenifer"),
						array("Titusz", "Leona", "Angéla"),
						array("Simon", "Emília"),
						array("Gáspár", "Menyhért", "Boldizsár"),
						array("Attila", "Ramóna", "Rajmund", "Bálint"),
						array("Gyöngyvér", "Szeverin", "Szörény"),
						array("Marcell", "Juliánusz"),
						array("Melánia", "Vilmos", "Vilma"),
						array("Ágota", "Honoráta"),
						array("Ernő", "Erneszta", "Tatjána"),
						array("Veronika", "Csongor", "Yvett"),
						array("Bódog", "Félix"),
						array("Lóránt", "Loránd", "Pál"),
						array("Gusztáv", "Marcell"),
						array("Antal", "Antónia"),
						array("Margit", "Piroska"),
						array("Sára", "Márta", "Márió"),
						array("Fábián", "Sebestyén"),
						array("Ágnes", "Agnéta"),
						array("Vince", "Artúr"),
						array("Zelma", "Rajmund", "Emerencia", "Emese"),
						array("Timót", "Ferenc"),
						array("Pál", "Henrik"),
						array("Vanda", "Paula", "Timóteusz"),
						array("Angéla", "Angelika"),
						array("Károly", "Karola", "Tamás"),
						array("Adél", "Valér"),
						array("Martina", "Gerda", "Jácinta"),
						array("Marcella", "János")
					),
					2		=>	array(
						array("Ignác", "Brigitta", "Kincső"),
						array("Karolina", "Karola", "Aida"),
						array("Balázs", "Oszkár", "Celerina"),
						array("Ráhel", "Csenge", "Veronika", "András"),
						array("Ágota", "Ingrid", "Etelka", "Léda"),
						array("Dorottya", "Dóra", "Pál"),
						array("Tódor", "Rómeó", "Richárd"),
						array("Aranka", "Jeromos"),
						array("Abigél", "Alex", "Apollónia"),
						array("Elvira"),
						array("Bertold", "Marietta"),
						array("Lívia", "Lídia", "Eulália"),
						array("Ella", "Linda", "Levente", "Katalin"),
						array("Bálint", "Valentin", "Cirill", "Metód"),
						array("Kolos", "Györgyi", "Georgina"),
						array("Julianna", "Lilla", "Filippa"),
						array("Donát"),
						array("Bernadett", "Simon", "Zenkő"),
						array("Zsuzsanna", "Eliza", "Konrád"),
						array("Aladár", "Álmos", "Leó"),
						array("Eleonóra", "Zelmira", "Péter"),
						array("Gerzson", "Margit", "Zétény"),
						array("Alfréd", "Polikárp", "Mirtill"),
						/* szökőnap */
						array("Mátyás", "Jázmin"),
						array("Géza", "Cézár", "Vanda"),
						array("Edina", "Viktor", "Győző"),
						array("Ákos", "Bátor", "Gábor"),
						array("Elemér", "Oszvald", "Román")
					),
					3		=>	array(
						array("Albin", "Albina", "Leonita", "Lea"),
						array("Lujza", "Ágnes", "Henrik", "Magor"),
						array("Kornélia", "Kunigunda", "Frigyes"),
						array("Kázmér", "Lúciusz", "Zorán"),
						array("Adorján", "Adrián"),
						array("Leonóra", "Inez", "Koletta"),
						array("Tamás", "Perpétua", "Felicitász"),
						array("János", "Zoltán", "Apolka"),
						array("Franciska", "Fanni"),
						array("Ildikó", "Emil", "Gusztáv"),
						array("Szilárd", "Tímea", "Konstantin"),
						array("Gergely", "Maximilián"),
						array("Krisztián", "Ajtony", "Egyed", "Patrícia"),
						array("Matild", "Matilda", "Trilla"),
						array("Kristóf", "Kelemen"),
						array("Henrietta", "Herbert"),
						array("Gertrúd", "Patrik"),
						array("Sándor", "Ede", "Cirill"),
						array("József", "Bánk"),
						array("Klaudia", "Alexandra"),
						array("Benedek", "Bence", "Miklós"),
						array("Beáta", "Izolda", "Lea"),
						array("Emőke", "Botond", "Ottó", "Kartal"),
						array("Gábor", "Karina"),
						array("Irén", "Írisz", "Lúcia"),
						array("Emánuel", "Emánuéla", "Larissza", "Árpád"),
						array("Hajnalka", "Lídia", "Auguszta"),
						array("Gedeon", "Johanna"),
						array("Auguszta", "Bertold"),
						array("Zalán"),
						array("Árpád", "Benjámin", "Benő")
					),
					4		=>	array(
						array("Hugó", "Agád"),
						array("Áron", "Ferenc"),
						array("Buda", "Richárd", "Hóvirág", "Indira"),
						array("Izidor"),
						array("Vince", "Irén", "Teodóra"),
						array("Vilmos", "Bíborka", "Taksony", "Celesztin"),
						array("Herman", "János"),
						array("Dénes", "Valér", "Valter"),
						array("Erhard", "Ákos", "Döme"),
						array("Zsolt", "Ezékiel"),
						array("Leó", "Szaniszló", "Glória"),
						array("Gyula", "Baldvin", "Sába"),
						array("Ida", "Márton", "Hermina"),
						array("Tibor"),
						array("Anasztázia", "Tas", "Oktávia"),
						array("Csongor", "Bernadett"),
						array("Rudolf", "Izidóra"),
						array("Andrea", "Ilma", "Apolló", "Aladár"),
						array("Emma", "Malvin", "Zseraldina"),
						array("Tivadar", "Tihamér", "Töhötöm"),
						array("Konrád", "Zelmira", "Anzelm"),
						array("Csilla", "Noémi", "Kájusz"),
						array("Béla", "Adalbert"),
						array("György", "Fidél", "Debóra"),
						array("Márk", "Ányos"),
						array("Ervin", "Klétusz"),
						array("Zita", "Mariann", "Anasztáz"),
						array("Valéria", "Péter"),
						array("Péter", "Katalin", "Roberta"),
						array("Katalin", "Kitti", "Zsófia", "Piusz")
					),
					5			=>	array(
						array("Fülöp", "Jakab", "Zsaklin", "Jefte", "József"),
						array("Zsigmond", "Atanáz", "Zoé"),
						array("Tímea", "Irma", "Jakab", "Fülöp"),
						array("Mónika", "Flórián"),
						array("Györgyi", "Irén"),
						array("Ivett", "Frida", "Judit", "Yvett"),
						array("Gizella", "Gusztáv", "Bendegúz"),
						array("Mihály", "Győző"),
						array("Gergely", "Katinka", "Alberta", "Édua"),
						array("Ármin", "Pálma", "Izidor"),
						array("Ferenc"),
						array("Pongrác"),
						array("Szervác", "Imola", "Imelda"),
						array("Bonifác", "Gyöngyi"),
						array("Zsófia", "Szonja", "Döníz"),
						array("Mózes", "Botond", "János"),
						array("Paszkál", "Ditmár", "Rezeda"),
						array("Erik", "Alexandra", "János"),
						array("Ivó", "Iván", "Milán"),
						array("Bernát", "Bernardin", "Felícia"),
						array("Konstantin", "András"),
						array("Júlia", "Rita", "Emil"),
						array("Dezső", "Vilmos", "Renáta"),
						array("Eszter", "Eliza", "Vanessza"),
						array("Orbán", "Gergely"),
						array("Fülöp", "Evelin"),
						array("Hella", "Pelbárt", "Ágoston"),
						array("Emil", "Csanád", "Vilmos"),
						array("Magdolna", "Magda", "Ervin", "Léna"),
						array("Janka", "Zsanett", "Johanna", "Nándor"),
						array("Angéla", "Petronella")
					),
					6		=>	array(
						array("Tünde", "Jusztinusz"),
						array("Kármen", "Anita", "Péter", "Marcellinusz"),
						array("Klotild", "Cecília", "Károly"),
						array("Bulcsú", "Kerény", "Kerubin"),
						array("Fatime", "Fatima", "Bonifác"),
						array("Norbert", "Norberta", "Cintia"),
						array("Róbert", "Robertina", "Arianna", "Fülöp", "Roberta"),
						array("Medárd", "Helga"),
						array("Félix", "Előd", "Annamária", "Annabella"),
						array("Margit", "Gréta"),
						array("Barnabás"),
						array("Villő", "Orfeusz", "Adelaida"),
						array("Antal", "Anett"),
						array("Vazul", "Elizeus", "Herta"),
						array("Jolán", "Vid", "Viola"),
						array("Jusztin", "Jusztina", "Auréliusz"),
						array("Laura", "Alida", "Alina", "Szabolcs", "Adolf", "Bató"),
						array("Arnold", "Levente", "Doloróza"),
						array("Gyárfás", "Romuald"),
						array("Rafael", "Dina"),
						array("Alajos", "Leila"),
						array("Paulina", "Tamás"),
						array("Zoltán", "Szultána"),
						array("János", "Iván"),
						array("Vilmos", "Viola", "Vilma"),
						array("János", "Pál", "Cirill"),
						array("László", "Sámson"),
						array("Levente", "Irén", "Iréneusz"),
						array("Péter", "Pál","Emőke", "Judit", "Petra", "Szulamit", "Ivett"),
						array("Pál")
					),
					7		=>	array(
						array("Tihamér", "Annamária", "Olivér", "Áron"),
						array("Ottó"),
						array("Kornél", "Soma", "Tamás"),
						array("Ulrik", "Erzsébet"),
						array("Emese", "Sarolta", "Lotti", "Antal"),
						array("Csaba", "Mária"),
						array("Apollónia", "Vilibald", "Bene"),
						array("Ellák", "Edgár", "Eperke"),
						array("Lukrécia", "Veronika", "Hajnalka"),
						array("Amália", "Melina", "Engelbert", "Ulrika"),
						array("Nóra", "Lili", "Nelli", "Benedek"),
						array("Izabella", "Dalma", "Eleonóra"),
						array("Jenő", "Henrik"),
						array("Örs", "Stella", "Kamil"),
						array("Örkény", "Henrik", "Roland", "Bonaventúra"),
						array("Valter", "Irma"),
						array("Endre", "Elek", "András"),
						array("Szömér", "Frigyes", "Milla", "Hedvig", "Mirkó"),
						array("Emília"),
						array("Illés", "Margaréta"),
						array("Dániel", "Daniella", "Lőrinc"),
						array("Magdolna", "Mária", "Magda"),
						array("Lenke", "Brigitta", "Apollinár"),
						array("Kinga", "Kunigunda", "Kincső", "Krisztina"),
						array("Kristóf", "Jakab"),
						array("Anna", "Anikó", "Joakim"),
						array("Olga", "Liliána", "Natália", "Pantaleon"),
						array("Szabolcs", "Alina", "Ince", "Győző"),
						array("Márta", "Flóra"),
						array("Judit", "Xénia", "Péter"),
						array("Oszkár", "Ignác", "Bató")
					),
					8		=>	array(
						array("Boglárka", "Nimród", "Alfonz"),
						array("Lehel"),
						array("Hermina", "Lídia", "Kamélia", "Mirtill"),
						array("Domonkos", "Dominik", "János", "Dominika"),
						array("Krisztina"),
						array("Berta", "Bettina"),
						array("Ibolya"),
						array("László", "Domonkos"),
						array("Emőd", "Román"),
						array("Lőrinc", "Blanka", "Csilla"),
						array("Zsuzsanna", "Tiborc", "Klára"),
						array("Klára", "Hilária", "Diána"),
						array("Ipoly", "Ince", "Vitália"),
						array("Marcell", "Maximilián"),
						array("Mária"),
						array("Ábrahám", "Rókus"),
						array("Jácint", "Réka", "Hetény"),
						array("Ilona", "Rajnald"),
						array("Huba", "Marián", "Emília"),
						array("István", "Bernát"),
						array("Sámuel", "Hajna", "Piusz"),
						array("Menyhért", "Mirjam"),
						array("Bence", "Róza", "Szidónia"),
						array("Bertalan", "Aliz", "Detre"),
						array("Lajos", "Patrícia"),
						array("Izsó", "Tália", "Natália", "Zamfira"),
						array("Gáspár", "Mónika"),
						array("Ágoston", "Mózes"),
						array("Beatrix", "Erna"),
						array("Rózsa", "Félix", "Letícia"),
						array("Erika", "Bella", "Arisztid")
					),
					9	=>	array(
						array("Egyed", "Egon", "Noémi", "Tamara"),
						array("Rebeka", "Dorina", "Renáta", "Ingrid", "István"),
						array("Hilda", "Gergely"),
						array("Rozália", "Róza", "Ida"),
						array("Viktor", "Lőrinc", "Ofélia"),
						array("Zakariás", "Beáta"),
						array("Regina"),
						array("Mária", "Adrienn"),
						array("Ádám", "Péter"),
						array("Nikolett", "Hunor", "Miklós"),
						array("Teodóra", "Jácint", "Igor", "Helga"),
						array("Mária", "Irma"),
						array("Kornél", "János"),
						array("Szeréna", "Roxána"),
						array("Enikő", "Melitta"),
						array("Edit", "Ciprián"),
						array("Zsófia", "Róbert"),
						array("Diána", "József"),
						array("Vilhelmina", "Januáriusz", "Dorián"),
						array("Friderika"),
						array("Máté", "Mirella", "Jónás"),
						array("Móric", "Tamás"),
						array("Tekla", "Líviusz", "Ila"),
						array("Gellért", "Gerda", "Mercédesz"),
						array("Eufrozina", "Kende"),
						array("Jusztina", "Kozma", "Damján"),
						array("Adalbert", "Vince"),
						array("Vencel", "Salamon"),
						array("Mihály", "Gábor", "Rafael", "Mirabella"),
						array("Jeromos", "Honória", "Hunor")
					),
					10		=>	array(
						array("Malvin", "Teréz"),
						array("Petra", "Örs"),
						array("Helga", "Évald"),
						array("Ferenc", "Hajnalka"),
						array("Aurél", "Placid", "Attila", "Rella"),
						array("Brúnó", "Renáta", "Renátó"),
						array("Amália", "Bekény"),
						array("Koppány", "Benedikta"),
						array("Dénes", "János"),
						array("Gedeon", "Ferenc", "Bendegúz"),
						array("Brigitta", "Placida", "Etel", "Gitta"),
						array("Miksa", "Rezső", "Edvin"),
						array("Kálmán", "Ede", "Edvárd"),
						array("Helén", "Kaldixtusz"),
						array("Teréz", "Aranka"),
						array("Gál", "Margit", "Hedvig"),
						array("Hedvig", "Ignác", "Rudolf"),
						array("Lukács", "Jusztusz"),
						array("Nándor", "János", "Pál"),
						array("Vendel", "Irén", "Kleopátra"),
						array("Orsolya", "Zsolt"),
						array("Előd", "Szalóme", "Kordélia"),
						array("Gyöngyvér", "János", "Gyöngyi"),
						array("Salamon", "Antal"),
						array("Blanka", "Bianka", "Mór"),
						array("Dömötör", "Armand", "Örs"),
						array("Szabina", "Antonietta"),
						array("Simon", "Szimonetta", "Szimóna", "Júdás", "Tádé"),
						array("Nárcisz", "Melinda", "Őzike"),
						array("Alfonz", "Zenóbia"),
						array("Farkas", "Rodrigó", "Wolfgang")
					),
					11		=>	array(
						array("Marianna"),
						array("Achilles", "Bató"),
						array("Győző", "Márton"),
						array("Károly", "Karola"),
						array("Imre", "Zakariás", "Tétény"),
						array("Lénárd", "Krisztina"),
						array("Csenger", "Rezső", "Ernő", "Florentin"),
						array("Zsombor", "Kolos", "Gottfrid"),
						array("Tivadar"),
						array("Réka", "András", "Leó"),
						array("Márton", "Atád", "Tódor"),
						array("Jónás", "Renátó", "Jozafát"),
						array("Szilvia", "Szaniszló"),
						array("Aliz", "Vanda", "Huba", "Klementina"),
						array("Albert", "Lipót"),
						array("Ödön", "Margit"),
						array("Hortenzia", "Gergő", "Dénes"),
						array("Jenő"),
						array("Erzsébet", "Zsóka"),
						array("Jolán", "Zsolt", "Ödön", "Bódog"),
						array("Olivér"),
						array("Cecília", "Filemon"),
						array("Kelemen", "Klementina", "Kolumbán"),
						array("Emma", "Flóra", "Virág"),
						array("Katalin", "Liza", "Katinka"),
						array("Virág", "Szvetlana", "Konrád", "Viktória", "Milos"),
						array("Virgil", "Virgínia"),
						array("Stefánia", "Jakab"),
						array("Taksony", "Ilma", "Filoména"),
						array("András", "Andor", "Andrea")
					),
					12		=>	array(
						array("Elza", "Natália", "Blanka", "Bonita"),
						array("Melinda", "Vivien", "Aranka"),
						array("Ferenc", "Olívia"),
						array("Borbála", "Barbara", "János"),
						array("Vilma", "Ünige", "Csaba"),
						array("Miklós", "Csinszka", "Gyopár", "Gyopárka"),
						array("Ambrus", "Ambrózia"),
						array("Mária", "Emőke"),
						array("Natália", "Valéria", "Filótea"),
						array("Judit", "Loretta", "Eulália"),
						array("Árpád", "Árpádina", "Damazusz"),
						array("Gabriella", "Johanna", "Franciska"),
						array("Luca", "Otília", "Lúcia", "Éda", "Tilia"),
						array("Szilárda", "Szilárd", "János"),
						array("Valér", "Detre"),
						array("Etelka", "Aletta", "Adelaida"),
						array("Lázár", "Olimpia"),
						array("Auguszta", "Gracián"),
						array("Viola", "Anasztáz"),
						array("Teofil", "Liberátusz"),
						array("Tamás", "Péter"),
						array("Zénó", "Flórián"),
						array("Viktória", "János"),
						array("Ádám", "Éva", "Adél"),
						array("Eugénia", "Anasztázia"),
						array("István"),
						array("János", "Teodor"),
						array("Kamilla", "Apor"),
						array("Tamás", "Tamara"),
						array("Dávid", "Hunor", "Libériusz"),
						array("Szilveszter", "Donáta")
					)
				);
				break;
			case "pl_PL":
				return array(
					1		=>	array(
						array("Mieczysław", "Mieczysława", "Mieszko"),
						array("Abel", "Achacy", "Achacjusz", "Aspazja", "Bazyli", "Izydor", "Jakobina", "Jakubina", "Makary", "Narcyz", "Stefania", "Strzeżysław", "Sylwester", "Sylwestra", "Telesfor", "Telesfora"),
						array("Danuta", "Piotr", "Genowefa"),
						array("Angelika", "Aniela", "Dobromir", "Eugeniusz", "Grzegorz", "Izabela"),
						array("Edward", "Emilian", "Hania", "Szymon"),
						array("Andrzej", "Bolemir", "Kacper", "Kasper"),
						array("Julian", "Lucjan", "Walenty"),
						array("Mścisław", "Seweryn"),
						array("Antoni", "Borzymir", "Julian", "Julianna"),
						array("Dobrosław", "Jan", "Paweł"),
						array("Feliks", "Krzesimir", "Matylda"),
						array("Antoni", "Arkadiusz", "Benedykt", "Czesław", "Czesława", "Ernest"),
						array("Bogumił", "Bogusława", "Weronika"),
						array("Feliks", "Radogost", "Felkis"),
						array("Aleksander", "Dąbrówka", "Dobrawa", "Domasław", "Paweł"),
						array("Marcel", "Włodzimierz", "Kevin"),
						array("Antoni", "Jan", "Rościsław"),
						array("Bogumił", "Jaropełk", "Krystyna", "Małgorzata", "Piotr"),
						array("Andrzej", "Bernard", "Erwin", "Henryk", "Mariusz", "Marta", "Racimir", "Sara"),
						array("Dobiegniew", "Fabian", "Sebastian"),
						array("Agnieszka", "Jarosław", "Jarosława", "Marcela"),
						array("Anastazy", "Dobromysł", "Dorian", "Marta", "Wincenty"),
						array("Jan", "Maria"),
						array("Felicja", "Mirogniew", "Rafaela", "Rafał", "Tymoteusz"),
						array("Miłosz", "Miłowan", "Miłowit", "Paweł", "Tatiana", "Maleszka"),
						array("Paula", "Paulina", "Wanda"),
						array("Angelika", "Ilona", "Julian"),
						array("Agnieszka", "Augustyn", "Julian", "Karol", "Piotr", "Radomir"),
						array("Hanna", "Walerian", "Zdzisław"),
						array("Feliks", "Gerard", "Maciej", "Marcin", "Martyna", "Sebastian"),
						array("Euzebiusz", "Jan", "Piotr")
					),
					2			=>	array(
						array("Dobrochna", "Iga", "Ignacy", "Paweł", "Siemirad", "Żegota"),
						array("Joanna", "Korneliusz", "Maria", "Miłosława", "Rory"),
						array("Błażej", "Maksym", "Oskar", "Stefan", "Telimena"),
						array("Andrzej", "Gilbert", "Jan", "Joanna", "Józef", "Weronika", "Witosława"),
						array("Aga", "Agata", "Jakub", "Jan", "Paweł", "Piotr"),
						array("Antoni", "Bogdan", "Bohdan", "Dorota", "Ksenia", "Szymon"),
						array("Alfons", "Parteniusz", "Partenia", "Romeusz", "Romuald", "Rozalia", "Ryszard", "Sulisław"),
						array("Gniewomir", "Jan", "Paweł", "Piotr", "Sebastian"),
						array("Bernard", "Eryk", "Eryka"),
						array("Gabriel", "Jacek", "Elwira"),
						array("Lucjan", "Maria", "Olgierd", "Świętomira"),
						array("Julian", "Laurenty", "Nora"),
						array("Grzegorz", "Jordan", "Katarzyna", "Toligniew"),
						array("Dobiesława", "Józef", "Konrad", "Krystyna", "Lilian", "Liliana", "Mikołaj", "Niemir", "Niemira", "Zenon", "Cyryl"),
						array("Georgina", "Jordan", "Jowita", "Józef", "Klaudiusz"),
						array("Bernard", "Dan", "Danuta", "Julianna"),
						array("Donata", "Franciszek", "Julian", "Konstanty", "Łukasz", "Niegomir", "Zbigniew", "Zbyszko"),
						array("Albert", "Alberta", "Krystiana", "Więcesława", "Zuzanna"),
						array("Arnold", "Henryk", "Konrad"),
						array("Leon", "Ludmiła", "Ludomiła"),
						array("Eleonora", "Feliks", "Teodor"),
						array("Marta", "Małgorzata", "Piotr", "Wiktor"),
						array("Bądzimir", "Damian", "Piotr", "Roma", "Seweryn"),
						array("Bogurad", "Bogusz", "Boguta", "Maciej", "Piotr"),
						array("Bolebor", "Cezary", "Maciej", "Małgorzata"),
						array("Aleksander", "Bogumił", "Cezariusz", "Mirosław", "Ewelina"),
						array("Aleksander", "Anastazja", "Gabriel", "Gabriela", "Sierosława"),
						array("Józef", "Roman", "Lech"),
						array("Dobronieg", "Roman")
					),
					3		=>	array(
						array("Albin", "Antoni", "Antonina", "Amelia", "Feliks", "Herakles", "Joanna", "Józef", "Piotr"),
						array("Franciszek", "Helena", "Henryk", "Krzysztof", "Michał", "Paweł", "Piotr", "Radosław"),
						array("Hieronim", "Maryna"),
						array("Adrian", "Adrianna", "Arkadiusz", "Eugeniusz", "Kazimierz", "Lucja"),
						array("Adrian", "Adrianna", "Fryderyk", "Jan", "Wacław", "Wacława"),
						array("Eugenia", "Jordan", "Klaudian", "Róża", "Wiktor", "Wojsław"),
						array("Felicja", "Paweł", "Tomasz"),
						array("Beata", "Jan", "Julian", "Miligost", "Miłogost", "Stefan"),
						array("Dominik", "Franciszka", "Katarzyna"),
						array("Aleksander", "Borzysław", "Cyprian"),
						array("Benedykt", "Drogosława", "Edwin", "Konstantyn", "Rozyna"),
						array("Bernard", "Blizbor", "Grzegorz", "Józefina"),
						array("Bożena", "Ernest", "Kasjan", "Krystyna", "Marek"),
						array("Bożeciecha", "Jakub", "Leon", "Matylda", "Michał"),
						array("Gościmir", "Klemens", "Krzysztof", "Ludwika"),
						array("Henryka", "Herbert", "Izabela"),
						array("Gertruda", "Jan", "Patryk", "Zbigniew", "Zbyszko"),
						array("Aleksander", "Boguchwał", "Cyryl", "Edward"),
						array("Bogdan", "Józef"),
						array("Aleksander", "Aleksandra", "Bogusław", "Klaudia"),
						array("Benedykt", "Lubomira", "Mikołaj"),
						array("Bogusław", "Katarzyna", "Kazimierz", "Paweł"),
						array("Feliks", "Katarzyna", "Piotr"),
						array("Gabriel", "Marek", "Szymon"),
						array("Ireneusz", "Łucja", "Lucja", "Lutomysł", "Maria", "Wieńczysław"),
						array("Emanuel", "Feliks", "Manuela", "Teodor"),
						array("Benedykt", "Ernest", "Jan", "Lidia", "Rupert"),
						array("Aniela", "Antoni", "Jan"),
						array("Cyryl"),
						array("Amelia", "Aniela", "Częstobor", "Jan"),
						array("Beniamin", "Dobromira", "Kornelia")
					),
					4		=>	array(
						array("Grażyna", "Katarzyna", "Teodora", "Tolisław", "Zbigniew", "Zbyszko"),
						array("Franciszek", "Sądomir", "Władysław", "Władysława"),
						array("Antoni", "Cieszygor", "Jakub", "Ryszard"),
						array("Benedykt", "Izydor", "Wacław", "Wacława"),
						array("Borzywoj", "Irena", "Wincenty", "Jam"),
						array("Ada", "Adam", "Ireneusz", "Katarzyna", "Świętobor"),
						array("Donata", "Przecław"),
						array("Cezary", "Radosław", "Sieciesława"),
						array("Dobrosława", "Dymitr", "Maja"),
						array("Antoni", "Daniel", "Henryk", "Małgorzata", "Michał"),
						array("Filip", "Jaromir", "Leon", "Marek"),
						array("Andrzej", "Iwan", "Juliusz", "Siemiodrog", "Wiktor", "Zenon"),
						array("Jan", "Justyn", "Małgorzata", "Marcin", "Przemysł", "Przemysław"),
						array("Julianna", "Justyn", "Maria", "Myślimir"),
						array("Anastazja", "Leonid", "Wacław", "Wacława"),
						array("Erwin", "Julia", "Ksenia", "Nikita", "Nosisław"),
						array("Jakub", "Józef", "Klara", "Radociech", "Robert", "Rudolf", "Stefan"),
						array("Bogusław", "Bogusława", "Gościsław"),
						array("Cieszyrad", "Czechasz", "Czesław", "Leon", "Tymon", "Werner", "Włodzimierz"),
						array("Agnieszka", "Czechoń", "Czesław", "Nawoj", "Szymon", "Teodor"),
						array("Bartosz", "Drogomił", "Feliks", "Konrad"),
						array("Kajus", "Kaja", "Łukasz", "Teodor"),
						array("Gerard", "Helena", "Jerzy", "Wojciech"),
						array("Aleksander", "Erwin", "Grzegorz"),
						array("Jarosław", "Marek"),
						array("Maria", "Marzena", "Spycimir"),
						array("Andrzej", "Bożebor", "Martyn", "Piotr", "Zyta"),
						array("Maria", "Paweł"),
						array("Angelina", "Augustyn", "Bogusław", "Piotr", "Robert"),
						array("Bartłomiej", "Jakub", "Katarzyna", "Marian")
					),
					5			=>	array(
						array("Aniela", "Filip", "Jakub", "Józef", "Lubomir", "Maja"),
						array("Walter", "Witomir", "Zygmunt", "Wouter"),
						array("Aleksander", "Antonina", "Maria", "Mariola", "Świętosława"),
						array("Grzegorz", "Michał", "Monika"),
						array("Irena", "Teodor", "Waldemar"),
						array("Gościwit", "Jan", "Judyta"),
						array("Benedykt", "Bogumir", "Ludmiła", "Ludomiła"),
						array("Marek", "Michał", "Piotr", "Stanisław"),
						array("Bożydar", "Grzegorz", "Karolina", "Mikołaj"),
						array("Częstomir", "Jan"),
						array("Filip", "Franciszek", "Iga", "Ignacy", "Lew", "Lutogniew", "Mira", "Żegota"),
						array("Dominik", "Jan", "Joanna", "Wszemił", "Pankracy"),
						array("Andrzej", "Ciechosław", "Gloria", "Magdalena", "Piotr", "Robert"),
						array("Dobiesław", "Wiktor", "Maciej"),
						array("Jan", "Zofia"),
						array("Andrzej", "Jędrzej", "Szymon", "Wieńczysław"),
						array("Bruno", "Sławomir", "Weronika", "Wiktor"),
						array("Aleksander", "Aleksandra", "Alicja", "Edwin", "Eryk", "Eryka", "Feliks", "Irena", "Myślibor"),
						array("Augustyn", "Celestyn", "Mikołaj", "Pękosław", "Piotr", "Timur"),
						array("Bronimir", "Teodor", "Wiktoria"),
						array("Donata", "Jan", "Tymoteusz", "Wiktor"),
						array("Emil", "Helena", "Jan", "Julia", "Ryta", "Wiesław", "Wiesława", "Wisława"),
						array("Budziwoj", "Emilia", "Iwona", "Jan", "Michał"),
						array("Cieszysława", "Jan", "Joanna", "Maria", "Zula", "Zuzanna"),
						array("Grzegorz", "Imisława", "Maria Magdalena"),
						array("Filip", "Marianna", "Paulina", "Ewelina", "Więcemił"),
						array("Jan", "Juliusz", "Lucjan", "Magdalena", "Radowit"),
						array("Augustyn", "Jaromir", "Wiktor", "Wrocimir"),
						array("Bogusława", "Maksymilian", "Maria", "Magdalena", "Teodor", "Urszula"),
						array("Feliks", "Joanna"),
						array("Aniela", "Bożysława", "Teodor")
					),
					6		=>	array(
						array("Bernard", "Jakub", "Konrad", "Magdalena", "Nikodem", "Symeon", "Świętopełk"),
						array("Eugeniusz", "Maria", "Marianna", "Mikołaj", "Piotr", "Racisław"),
						array("Konstantyn", "Leszek", "Paula", "Tamara"),
						array("Franciszek", "Gościmił", "Karol"),
						array("Dobrociech", "Dobromir", "Dobrymir"),
						array("Dominika", "Norbert", "Paulina", "Więcerad"),
						array("Antoni", "Ciechomir", "Jarosław", "Paweł", "Robert", "Wiesław", "Wisław"),
						array("Maksym", "Seweryn", "Wyszesław"),
						array("Felicjan"),
						array("Bogumił", "Edgar", "Małgorzata"),
						array("Feliks", "Radomił"),
						array("Antonina", "Jan", "Leon", "Wyszemir"),
						array("Antoni", "Chociemir", "Lucjan", "Maria Magdalena", "Tobiasz"),
						array("Eliza", "Justyn", "Justyna", "Ninogniew"),
						array("Angelina", "Jolanta", "Witold", "Witołd", "Witolda", "Witosław"),
						array("Alina", "Aneta", "Budzimir", "Jan", "Justyna"),
						array("Agnieszka", "Drogomysł", "Franciszek", "Laura", "Marcjan", "Radomił"),
						array("Elżbieta", "Marek", "Marina", "Paula"),
						array("Julianna"),
						array("Bogna", "Bogumiła", "Bożena", "Franciszek", "Michał", "Rafaela", "Rafał"),
						array("Alicja", "Domamir", "Marta", "Teodor"),
						array("Broniwoj", "Paulina"),
						array("Józef", "Piotr", "Wanda", "Zenon"),
						array("Dan", "Danisz", "Danuta", "Emilia", "Jan"),
						array("Lucja", "Łucja", "Tolisława"),
						array("Jan", "Paweł"),
						array("Maria Magdalena", "Władysław", "Władysława"),
						array("Ireneusz", "Józef", "Leon", "Paweł"),
						array("Dalebor", "Paweł", "Piotr"),
						array("Ciechosława", "Emilia", "Lucyna")
					),
					7		=>	array(
						array("Halina", "Marian"),
						array("Maria", "Piotr", "Jagoda"),
						array("Jacek", "Leon", "Miłosław"),
						array("Elżbieta", "Józef", "Julian", "Teodor", "Wielisław"),
						array("Antoni", "Bartłomiej", "Jakub", "Karolina", "Michał"),
						array("Chociebor", "Dominik", "Dominika", "Łucja", "Lucja", "Niegosław"),
						array("Antoni", "Kira", "Piotr"),
						array("Adrian", "Adrianna", "Chwalimir", "Edgar", "Elżbieta", "Eugeniusz"),
						array("Łucja", "Lucja", "Mikołaj", "Weronika", "Zenon"),
						array("Aleksander", "Amelia", "Aniela", "Filip"),
						array("Cyprian", "Kalina", "Olga"),
						array("Andrzej", "Euzebiusz", "Feliks", "Henryk", "Paweł", "Piotr", "Tolimir", "Weronika"),
						array("Ernest", "Eugeniusz", "Jakub", "Justyna", "Małgorzata", "Radomiła", "Sara"),
						array("Damian", "Dobrogost", "Franciszek", "Izabela", "Marcelina"),
						array("Daniel", "Dawid", "Henryk", "Iga", "Ignacy", "Lubomysł", "Niecisław", "Włodzimierz", "Żegota"),
						array("Andrzej", "Maria Magdalena", "Marika", "Stefan"),
						array("Aleksander", "Andrzej", "Bogdan", "Marcelina", "Maria Magdalena"),
						array("Erwin", "Kamil", "Karolina", "Robert", "Szymon", "Unisław"),
						array("Lutobor", "Wincenty"),
						array("Czechoń", "Czesław", "Małgorzata", "Paweł"),
						array("Andrzej", "Daniel", "Paulina", "Stojsław", "Wiktor"),
						array("Bolesława", "Bolisława", "Maria Magdalena", "Milenia", "Więcemiła"),
						array("Bogna", "Żelisław"),
						array("Antoni", "Kinga", "Krystyna", "Olga", "Wojciecha"),
						array("Jakub", "Krzysztof", "Sławosz", "Walentyna"),
						array("Anna", "Baldev", "Grażyna", "Mirosława"),
						array("Julia", "Marta", "Natalia"),
						array("Marcela", "Świętomir", "Wiktor"),
						array("Konstantyn", "Maria", "Marta"),
						array("Julia", "Julita", "Ludmiła", "Maryna"),
						array("Emilian", "Helena", "Iga", "Ignacy", "Ludomir")
					),
					8		=>	array(
						array("Konrad", "Piotr"),
						array("Borzysława", "Karina", "Maria", "Stefan"),
						array("Augusta", "Lidia", "Nikodem", "Szczepan"),
						array("Dominik", "Maria", "Mironieg"),
						array("Emil", "Maria", "Stanisława"),
						array("Jakub", "Sława", "Stefan", "Wincenty"),
						array("Anna", "Dobiemir", "Donata", "Dorota", "Kajetan"),
						array("Cyprian", "Cyryl", "Emil", "Emilian", "Emiliusz"),
						array("Jan", "Klarysa", "Miłorad", "Roman"),
						array("Bogdan", "Borys"),
						array("Aleksander", "Włodzimierz", "Włodziwoj", "Zula", "Zuzanna"),
						array("Klara", "Lech", "Piotr"),
						array("Diana", "Helena", "Jan", "Kasjan", "Radomiła", "Wojbor"),
						array("Dobrowoj", "Euzebiusz"),
						array("Maria", "Stefan"),
						array("Domarad", "Domarat", "Joachim"),
						array("Anastazja", "Angelika", "Anita", "Eliza", "Jacek", "Jaczewoj", "Joanna", "Julianna", "Miron", "Żanna"),
						array("Bogusława", "Bronisław", "Bronisz", "Helena", "Ilona", "Klara"),
						array("Bolesław", "Emilia", "Jan", "Julian", "Juliusz", "Piotr"),
						array("Jan", "Samuel", "Samuela", "Sieciech", "Sobiesław", "Świeciech"),
						array("Emilian", "Filipina", "Franciszek", "Joanna", "Kazimiera", "Męcimir"),
						array("Cezary", "Dalegor", "Maria", "Namysław", "Tymoteusz", "Zygfryd"),
						array("Filip", "Laurenty"),
						array("Bartłomiej", "Cieszymir", "Jerzy", "Joanna", "Malina", "Michalina"),
						array("Grzegorz", "Luiza", "Michał", "Sieciesław"),
						array("Dobroniega", "Joanna", "Konstanty", "Maksym", "Maria"),
						array("Cezary", "Józef", "Monika", "Małgorzata", "Teodor"),
						array("Adelina", "Aleksander", "Aleksy", "Augustyn", "Patrycja", "Sobiesław", "Stronisław"),
						array("Gita", "Jan", "Racibor", "Sabina"),
						array("Częstowoj", "Miron", "Rebeka", "Róża", "Szczęsna", "Szczęsny"),
						array("Bohdan", "Paulina", "Rajmund", "Świętosław")
					),
					9	=>	array(
						array("Bronisław", "Bronisława", "Bronisz"),
						array("Bohdan", "Czesław", "Eliza", "Henryk", "Julian", "Stefan", "Tobiasz", "Witomysł"),
						array("Antoni", "Bartłomiej", "Bronisław", "Bronisz", "Izabela", "Jan", "Joachim", "Mojmir", "Szymon", "Wincenty", "Zenon"),
						array("Ida", "Lilianna", "Rościgniew", "Róża", "Rozalia"),
						array("Dorota", "Justyna", "Stronisława", "Wawrzyniec"),
						array("Albin", "Beata", "Eugenia", "Eugeniusz", "Michał", "Uniewit"),
						array("Domasława", "Domisława", "Marek", "Regina", "Rena", "Ryszard"),
						array("Adrian", "Adrianna", "Maria", "Radosław", "Radosława", "Klementyna"),
						array("Augustyna", "Aureliusz", "Piotr", "Ścibor", "Ścibora", "Sergiusz", "Sobiesąd"),
						array("Aldona", "Łukasz", "Mikołaj", "Mścibor"),
						array("Feliks", "Jacek", "Jan", "Naczesław"),
						array("Amadeusz", "Maria", "Piotr", "Sylwin"),
						array("Aleksander", "Eugenia", "Filip", "Lubor", "Morzysław", "Szeliga"),
						array("Bernard", "Cyprian", "Roksana", "Siemomysł", "Szymon"),
						array("Maria", "Nikodem"),
						array("Cyprian", "Edyta", "Eugenia", "Franciszek", "Kamila", "Kornel", "Lucja", "Łucja", "Wiktor"),
						array("Drogosław", "Franciszek", "Justyn", "Justyna", "Teodora"),
						array("Dobrowit", "Irena", "Józef", "Stefania"),
						array("Konstancja", "Teodor", "Więcemir"),
						array("Agnieszka", "Barbara", "Dionizy", "Eustachiusz", "Eustachy", "Fausta", "Faustyna", "Filipina", "Irena", "Klemens", "Mieczysława", "Miłowuj", "Oleg", "Perpetua", "Protazy"),
						array("Bożeciech", "Bożydar", "Jonasz", "Laurenty", "Mateusz", "Mira"),
						array("Joachim", "Maurycy", "Prosimir", "Scott", "Tomasz"),
						array("Boguchwała", "Bogusław", "Elżbieta", "Krzysztof", "Libert", "Litoriusz", "Liwiusz", "Piotr", "Tekla", "Zachariusz"),
						array("Gerard", "Maria", "Teodor", "Tomir", "Uniegost"),
						array("Aurelia", "Franciszek", "Kamil", "Ładysław", "Piotr", "Świętopełk", "Wincenty", "Władysław", "Władysława"),
						array("Cyprian", "Euzebiusz", "Justyna", "Łękomir"),
						array("Amadeusz", "Damian"),
						array("Jan", "Luba", "Lubosza", "Marek", "Nikita", "Sylwin", "Wacław", "Wacława", "Więcesław"),
						array("Michał", "Rafał", "Gabriel"),
						array("Grzegorz", "Hieronim", "Honoriusz", "Imisław", "Rachela", "Wera", "Wiera", "Wiktor", "Zofia")
					),
					10		=>	array(
						array("Danuta", "Remigiusz", "Cieszysław", "Dan", "Danisz", "Danuta", "Igor", "Jan", "Remigiusz"),
						array("Stanimir", "Teofil"),
						array("Gerard", "Józefa", "Sierosław", "Teresa"),
						array("Edwin", "Franciszek", "Konrad", "Rozalia"),
						array("Częstogniew", "Donata", "Igor", "Justyn", "Konstancjusz"),
						array("Artur", "Bronisław", "Bronisz", "Emil", "Roman"),
						array("Justyna", "Marek", "Maria", "Rościsława", "Stefan"),
						array("Bryda", "Brygida", "Laurencja", "Marcin", "Wojsława"),
						array("Bogdan", "Jan", "Ludwik"),
						array("Franciszek", "Lutomir", "Tomił"),
						array("Aldona", "Dobromiła", "Emil", "Emilian", "Emiliusz", "Maria", "Marian"),
						array("Maksymilian", "Witold"),
						array("Daniel", "Edward", "Mikołaj", "Siemisław"),
						array("Alan", "Bernard", "Dominik"),
						array("Jadwiga", "Teresa"),
						array("Aurelia", "Gerard", "Grzegorz"),
						array("Lucyna", "Małgorzata", "Marian", "Wiktor"),
						array("Julian", "Łukasz"),
						array("Ferdynand", "Piotr", "Siemowit", "Skarbimir", "Ziemowit"),
						array("Irena", "Urszula"),
						array("Bernard", "Celina", "Dobromił", "Elżbieta"),
						array("Filip", "Halka"),
						array("Iga", "Ignacy", "Jan", "Marlena", "Roman", "Seweryn", "Teodor", "Włościsław", "Żegota"),
						array("Antoni", "Boleczest", "Filip", "Marcin", "Rafaela", "Rafał"),
						array("Daria", "Kryspin", "Sambor", "Taras"),
						array("Dymitriusz", "Łucjan", "Lucyna", "Ludmiła", "Lutosław"),
						array("Iwona", "Sabina", "Wincenty"),
						array("Szymon", "Tadeusz", "Wszeciech"),
						array("Euzebia", "Franciszek", "Lubogost", "Teodor", "Wioletta"),
						array("Edmund", "Klaudiusz", "Przemysław", "Sądosław"),
						array("Antoni", "Antonina", "Godzimir", "Lucylla", "Łukasz", "Dezemir")
					),
					11		=>	array(
						array("Andrzej", "Seweryn", "Warcisław", "Wiktoryna"),
						array("Bohdana", "Bożydar", "Małgorzata", "Stojmir", "Tobiasz"),
						array("Bogumił", "Cezary", "Chwalisław", "Hubert", "Sylwia"),
						array("Mściwój", "Olgierd", "Karol"),
						array("Dalemir", "Elżbieta", "Florian", "Sławomir"),
						array("Feliks", "Leonard", "Trzebowit", "Ziemowit"),
						array("Antoni", "Florentyn", "Przemił"),
						array("Dymitr", "Klaudiusz", "Seweryn", "Wiktor"),
						array("Bogudar", "Genowefa", "Teodor", "Ursyn"),
						array("Andrzej", "Lena", "Leon", "Ludomir", "Stefan"),
						array("Anastazja", "Bartłomiej", "Maciej", "Marcin", "Spycisław", "Teodor"),
						array("Cibor", "Czcibor", "Jonasz", "Krystyn", "Marcin", "Renata", "Witold"),
						array("Arkadiusz", "Eugeniusz", "Jan", "Mikołaj", "Stanisław"),
						array("Aga", "Agata", "Damian", "Elżbieta", "Emil", "Emiliusz", "Józef", "Judyta", "Ścibor", "Ścibora", "Wszerad"),
						array("Albert", "Alfons", "Artur", "Gurias", "Idalia", "Józef", "Leopold", "Leopoldyna", "Przybygniew", "Roger"),
						array("Edmund", "Marek", "Maria", "Niedamir", "Otomar", "Paweł", "Piotr"),
						array("Grzegorz"),
						array("Aniela", "Cieszymysł", "Klaudyna", "Roman", "Tomasz"),
						array("Elżbieta", "Mironiega", "Paweł", "Seweryn"),
						array("Edmund", "Feliks", "Sędzimir"),
						array("Janusz", "Konrad", "Maria", "Piotr", "Regina", "Rena", "Twardosław", "Wiesław"),
						array("Cecylia", "Marek", "Wszemiła"),
						array("Adela", "Klemens", "Przedwoj"),
						array("Dobrosław", "Emilia", "Emma", "Franciszek", "Gerard", "Jan", "Pęcisław"),
						array("Katarzyna", "Tęgomir"),
						array("Dobiemiest", "Jan", "Konrad", "Lechosław", "Lechosława", "Leonard", "Sylwester"),
						array("Dominik", "Maksymilian", "Stojgniew", "Walery"),
						array("Gościrad", "Grzegorz", "Jakub", "Lesław", "Lesława", "Zdzisław"),
						array("Błażej", "Bolemysł", "Fryderyk", "Przemysł"),
						array("Andrzej", "Justyna", "Konstanty")
					),
					12		=>	array(
						array("Blanka", "Długosz", "Edmund", "Iwa", "Natalia", "Sobiesława"),
						array("Aurelia", "Balbina", "Bibiana", "Budzisław", "Budzisława", "Ludwina", "Paulina", "Sulisław", "Sylweriusz", "Sylwery", "Wiktoryn", "Zbylut"),
						array("Franciszek", "Kasjan", "Lucjusz", "Unimir"),
						array("Barbara", "Hieronim", "Krystian", "Piotr"),
						array("Gerald", "Krystyna", "Pęcisława"),
						array("Emilian", "Jarogniew", "Mikołaj"),
						array("Marcin", "Ninomysł"),
						array("Boguwola", "Maria", "Światozar"),
						array("Joachim", "Wielisława", "Wiesław"),
						array("Andrzej", "Daniel", "Judyta", "Julia", "Maria"),
						array("Daniela", "Julia", "Stefan", "Waldemar", "Wojmir"),
						array("Aleksander", "Dagmara"),
						array("Lucja", "Łucja", "Otylia"),
						array("Alfred", "Izydor", "Sławobor"),
						array("Celina", "Iga", "Ignacy", "Krystiana", "Nina", "Wolimir", "Żegota"),
						array("Alina", "Zdzisława"),
						array("Florian", "Jolanta", "Żyrosław"),
						array("Bogusław", "Gracjan", "Laurencja", "Wszemir"),
						array("Beniamin", "Dariusz", "Gabriela", "Mścigniew", "Tymoteusz"),
						array("Bogumiła", "Dominik"),
						array("Tomasz", "Tomisław"),
						array("Beata", "Drogomir", "Franciszka", "Zenon"),
						array("Sławomir", "Sławomira", "Wiktoria"),
						array("Adam", "Adamina", "Adela", "Ewa", "Ewelina", "Grzegorz"),
						array("Anastazja", "Eugenia", "Piotr"),
						array("Szczepan", "Wróciwoj"),
						array("Cezary", "Jan", "Radomysł"),
						array("Antoni", "Dobrowiest", "Emma"),
						array("Domawit", "Dominik", "Gosław", "Jonatan", "Marcin", "Tomasz"),
						array("Dawid", "Eugeniusz", "Katarzyna", "Uniedrog"),
						array("Korneliusz", "Melania", "Sebastian", "Sylwester", "Tworzysław")
					)
				);
				break;
			default:
				echo "There is no such country.";
		}
		
	}
}

?>