<?php

namespace Icetee\Nameday\Seeds;

class NamedayList
{
    public static function getNamedays()
    {
        return [
            'hu_HU' => [
                1 => [
                    ["Alpár", "Fruzsina", "Bazil"],
                    ["Ábel", "Gergely", "Vazul"],
                    ["Genovéva", "Gyöngyvér", "Benjámin", "Dzsenifer"],
                    ["Titusz", "Leona", "Angéla"],
                    ["Simon", "Emília"],
                    ["Gáspár", "Menyhért", "Boldizsár"],
                    ["Attila", "Ramóna", "Rajmund", "Bálint"],
                    ["Gyöngyvér", "Szeverin", "Szörény"],
                    ["Marcell", "Juliánusz"],
                    ["Melánia", "Vilmos", "Vilma"],
                    ["Ágota", "Honoráta"],
                    ["Ernő", "Erneszta", "Tatjána"],
                    ["Veronika", "Csongor", "Yvett"],
                    ["Bódog", "Félix"],
                    ["Lóránt", "Loránd", "Pál"],
                    ["Gusztáv", "Marcell"],
                    ["Antal", "Antónia"],
                    ["Margit", "Piroska"],
                    ["Sára", "Márta", "Márió"],
                    ["Fábián", "Sebestyén"],
                    ["Ágnes", "Agnéta"],
                    ["Vince", "Artúr"],
                    ["Zelma", "Rajmund", "Emerencia", "Emese"],
                    ["Timót", "Ferenc"],
                    ["Pál", "Henrik"],
                    ["Vanda", "Paula", "Timóteusz"],
                    ["Angéla", "Angelika"],
                    ["Károly", "Karola", "Tamás"],
                    ["Adél", "Valér"],
                    ["Martina", "Gerda", "Jácinta"],
                    ["Marcella", "János"],
                ],
                2 => [
                    ["Ignác", "Brigitta", "Kincső"],
                    ["Karolina", "Karola", "Aida"],
                    ["Balázs", "Oszkár", "Celerina"],
                    ["Ráhel", "Csenge", "Veronika", "András"],
                    ["Ágota", "Ingrid", "Etelka", "Léda"],
                    ["Dorottya", "Dóra", "Pál"],
                    ["Tódor", "Rómeó", "Richárd"],
                    ["Aranka", "Jeromos"],
                    ["Abigél", "Alex", "Apollónia"],
                    ["Elvira"],
                    ["Bertold", "Marietta"],
                    ["Lívia", "Lídia", "Eulália"],
                    ["Ella", "Linda", "Levente", "Katalin"],
                    ["Bálint", "Valentin", "Cirill", "Metód"],
                    ["Kolos", "Györgyi", "Georgina"],
                    ["Julianna", "Lilla", "Filippa"],
                    ["Donát"],
                    ["Bernadett", "Simon", "Zenkő"],
                    ["Zsuzsanna", "Eliza", "Konrád"],
                    ["Aladár", "Álmos", "Leó"],
                    ["Eleonóra", "Zelmira", "Péter"],
                    ["Gerzson", "Margit", "Zétény"],
                    ["Alfréd", "Polikárp", "Mirtill"],
                    /* leap */
                    ["Mátyás", "Jázmin"],
                    ["Géza", "Cézár", "Vanda"],
                    ["Edina", "Viktor", "Győző"],
                    ["Ákos", "Bátor", "Gábor"],
                    ["Elemér", "Oszvald", "Román"],
                ],
                3 => [
                    ["Albin", "Albina", "Leonita", "Lea"],
                    ["Lujza", "Ágnes", "Henrik", "Magor"],
                    ["Kornélia", "Kunigunda", "Frigyes"],
                    ["Kázmér", "Lúciusz", "Zorán"],
                    ["Adorján", "Adrián"],
                    ["Leonóra", "Inez", "Koletta"],
                    ["Tamás", "Perpétua", "Felicitász"],
                    ["János", "Zoltán", "Apolka"],
                    ["Franciska", "Fanni"],
                    ["Ildikó", "Emil", "Gusztáv"],
                    ["Szilárd", "Tímea", "Konstantin"],
                    ["Gergely", "Maximilián"],
                    ["Krisztián", "Ajtony", "Egyed", "Patrícia"],
                    ["Matild", "Matilda", "Trilla"],
                    ["Kristóf", "Kelemen"],
                    ["Henrietta", "Herbert"],
                    ["Gertrúd", "Patrik"],
                    ["Sándor", "Ede", "Cirill"],
                    ["József", "Bánk"],
                    ["Klaudia", "Alexandra"],
                    ["Benedek", "Bence", "Miklós"],
                    ["Beáta", "Izolda", "Lea"],
                    ["Emőke", "Botond", "Ottó", "Kartal"],
                    ["Gábor", "Karina"],
                    ["Irén", "Írisz", "Lúcia"],
                    ["Emánuel", "Emánuéla", "Larissza", "Árpád"],
                    ["Hajnalka", "Lídia", "Auguszta"],
                    ["Gedeon", "Johanna"],
                    ["Auguszta", "Bertold"],
                    ["Zalán"],
                    ["Árpád", "Benjámin", "Benő"],
                ],
                4 => [
                    ["Hugó", "Agád"],
                    ["Áron", "Ferenc"],
                    ["Buda", "Richárd", "Hóvirág", "Indira"],
                    ["Izidor"],
                    ["Vince", "Irén", "Teodóra"],
                    ["Vilmos", "Bíborka", "Taksony", "Celesztin"],
                    ["Herman", "János"],
                    ["Dénes", "Valér", "Valter"],
                    ["Erhard", "Ákos", "Döme"],
                    ["Zsolt", "Ezékiel"],
                    ["Leó", "Szaniszló", "Glória"],
                    ["Gyula", "Baldvin", "Sába"],
                    ["Ida", "Márton", "Hermina"],
                    ["Tibor"],
                    ["Anasztázia", "Tas", "Oktávia"],
                    ["Csongor", "Bernadett"],
                    ["Rudolf", "Izidóra"],
                    ["Andrea", "Ilma", "Apolló", "Aladár"],
                    ["Emma", "Malvin", "Zseraldina"],
                    ["Tivadar", "Tihamér", "Töhötöm"],
                    ["Konrád", "Zelmira", "Anzelm"],
                    ["Csilla", "Noémi", "Kájusz"],
                    ["Béla", "Adalbert"],
                    ["György", "Fidél", "Debóra"],
                    ["Márk", "Ányos"],
                    ["Ervin", "Klétusz"],
                    ["Zita", "Mariann", "Anasztáz"],
                    ["Valéria", "Péter"],
                    ["Péter", "Katalin", "Roberta"],
                    ["Katalin", "Kitti", "Zsófia", "Piusz"],
                ],
                5 => [
                    ["Fülöp", "Jakab", "Zsaklin", "Jefte", "József"],
                    ["Zsigmond", "Atanáz", "Zoé"],
                    ["Tímea", "Irma", "Jakab", "Fülöp"],
                    ["Mónika", "Flórián"],
                    ["Györgyi", "Irén"],
                    ["Ivett", "Frida", "Judit", "Yvett"],
                    ["Gizella", "Gusztáv", "Bendegúz"],
                    ["Mihály", "Győző"],
                    ["Gergely", "Katinka", "Alberta", "Édua"],
                    ["Ármin", "Pálma", "Izidor"],
                    ["Ferenc"],
                    ["Pongrác"],
                    ["Szervác", "Imola", "Imelda"],
                    ["Bonifác", "Gyöngyi"],
                    ["Zsófia", "Szonja", "Döníz"],
                    ["Mózes", "Botond", "János"],
                    ["Paszkál", "Ditmár", "Rezeda"],
                    ["Erik", "Alexandra", "János"],
                    ["Ivó", "Iván", "Milán"],
                    ["Bernát", "Bernardin", "Felícia"],
                    ["Konstantin", "András"],
                    ["Júlia", "Rita", "Emil"],
                    ["Dezső", "Vilmos", "Renáta"],
                    ["Eszter", "Eliza", "Vanessza"],
                    ["Orbán", "Gergely"],
                    ["Fülöp", "Evelin"],
                    ["Hella", "Pelbárt", "Ágoston"],
                    ["Emil", "Csanád", "Vilmos"],
                    ["Magdolna", "Magda", "Ervin", "Léna"],
                    ["Janka", "Zsanett", "Johanna", "Nándor"],
                    ["Angéla", "Petronella"],
                ],
                6 => [
                    ["Tünde", "Jusztinusz"],
                    ["Kármen", "Anita", "Péter", "Marcellinusz"],
                    ["Klotild", "Cecília", "Károly"],
                    ["Bulcsú", "Kerény", "Kerubin"],
                    ["Fatime", "Fatima", "Bonifác"],
                    ["Norbert", "Norberta", "Cintia"],
                    ["Róbert", "Robertina", "Arianna", "Fülöp", "Roberta"],
                    ["Medárd", "Helga"],
                    ["Félix", "Előd", "Annamária", "Annabella"],
                    ["Margit", "Gréta"],
                    ["Barnabás"],
                    ["Villő", "Orfeusz", "Adelaida"],
                    ["Antal", "Anett"],
                    ["Vazul", "Elizeus", "Herta"],
                    ["Jolán", "Vid", "Viola"],
                    ["Jusztin", "Jusztina", "Auréliusz"],
                    ["Laura", "Alida", "Alina", "Szabolcs", "Adolf", "Bató"],
                    ["Arnold", "Levente", "Doloróza"],
                    ["Gyárfás", "Romuald"],
                    ["Rafael", "Dina"],
                    ["Alajos", "Leila"],
                    ["Paulina", "Tamás"],
                    ["Zoltán", "Szultána"],
                    ["János", "Iván"],
                    ["Vilmos", "Viola", "Vilma"],
                    ["János", "Pál", "Cirill"],
                    ["László", "Sámson"],
                    ["Levente", "Irén", "Iréneusz"],
                    ["Péter", "Pál","Emőke", "Judit", "Petra", "Szulamit", "Ivett"],
                    ["Pál"],
                ],
                7 => [
                    ["Tihamér", "Annamária", "Olivér", "Áron"],
                    ["Ottó"],
                    ["Kornél", "Soma", "Tamás"],
                    ["Ulrik", "Erzsébet"],
                    ["Emese", "Sarolta", "Lotti", "Antal"],
                    ["Csaba", "Mária"],
                    ["Apollónia", "Vilibald", "Bene"],
                    ["Ellák", "Edgár", "Eperke"],
                    ["Lukrécia", "Veronika", "Hajnalka"],
                    ["Amália", "Melina", "Engelbert", "Ulrika"],
                    ["Nóra", "Lili", "Nelli", "Benedek"],
                    ["Izabella", "Dalma", "Eleonóra"],
                    ["Jenő", "Henrik"],
                    ["Örs", "Stella", "Kamil"],
                    ["Örkény", "Henrik", "Roland", "Bonaventúra"],
                    ["Valter", "Irma"],
                    ["Endre", "Elek", "András"],
                    ["Szömér", "Frigyes", "Milla", "Hedvig", "Mirkó"],
                    ["Emília"],
                    ["Illés", "Margaréta"],
                    ["Dániel", "Daniella", "Lőrinc"],
                    ["Magdolna", "Mária", "Magda"],
                    ["Lenke", "Brigitta", "Apollinár"],
                    ["Kinga", "Kunigunda", "Kincső", "Krisztina"],
                    ["Kristóf", "Jakab"],
                    ["Anna", "Anikó", "Joakim"],
                    ["Olga", "Liliána", "Natália", "Pantaleon"],
                    ["Szabolcs", "Alina", "Ince", "Győző"],
                    ["Márta", "Flóra"],
                    ["Judit", "Xénia", "Péter"],
                    ["Oszkár", "Ignác", "Bató"],
                ],
                8 => [
                    ["Boglárka", "Nimród", "Alfonz"],
                    ["Lehel"],
                    ["Hermina", "Lídia", "Kamélia", "Mirtill"],
                    ["Domonkos", "Dominik", "János", "Dominika"],
                    ["Krisztina"],
                    ["Berta", "Bettina"],
                    ["Ibolya"],
                    ["László", "Domonkos"],
                    ["Emőd", "Román"],
                    ["Lőrinc", "Blanka", "Csilla"],
                    ["Zsuzsanna", "Tiborc", "Klára"],
                    ["Klára", "Hilária", "Diána"],
                    ["Ipoly", "Ince", "Vitália"],
                    ["Marcell", "Maximilián"],
                    ["Mária"],
                    ["Ábrahám", "Rókus"],
                    ["Jácint", "Réka", "Hetény"],
                    ["Ilona", "Rajnald"],
                    ["Huba", "Marián", "Emília"],
                    ["István", "Bernát"],
                    ["Sámuel", "Hajna", "Piusz"],
                    ["Menyhért", "Mirjam"],
                    ["Bence", "Róza", "Szidónia"],
                    ["Bertalan", "Aliz", "Detre"],
                    ["Lajos", "Patrícia"],
                    ["Izsó", "Tália", "Natália", "Zamfira"],
                    ["Gáspár", "Mónika"],
                    ["Ágoston", "Mózes"],
                    ["Beatrix", "Erna"],
                    ["Rózsa", "Félix", "Letícia"],
                    ["Erika", "Bella", "Arisztid"],
                ],
                9 => [
                    ["Egyed", "Egon", "Noémi", "Tamara"],
                    ["Rebeka", "Dorina", "Renáta", "Ingrid", "István"],
                    ["Hilda", "Gergely"],
                    ["Rozália", "Róza", "Ida"],
                    ["Viktor", "Lőrinc", "Ofélia"],
                    ["Zakariás", "Beáta"],
                    ["Regina"],
                    ["Mária", "Adrienn"],
                    ["Ádám", "Péter"],
                    ["Nikolett", "Hunor", "Miklós"],
                    ["Teodóra", "Jácint", "Igor", "Helga"],
                    ["Mária", "Irma"],
                    ["Kornél", "János"],
                    ["Szeréna", "Roxána"],
                    ["Enikő", "Melitta"],
                    ["Edit", "Ciprián"],
                    ["Zsófia", "Róbert"],
                    ["Diána", "József"],
                    ["Vilhelmina", "Januáriusz", "Dorián"],
                    ["Friderika"],
                    ["Máté", "Mirella", "Jónás"],
                    ["Móric", "Tamás"],
                    ["Tekla", "Líviusz", "Ila"],
                    ["Gellért", "Gerda", "Mercédesz"],
                    ["Eufrozina", "Kende"],
                    ["Jusztina", "Kozma", "Damján"],
                    ["Adalbert", "Vince"],
                    ["Vencel", "Salamon"],
                    ["Mihály", "Gábor", "Rafael", "Mirabella"],
                    ["Jeromos", "Honória", "Hunor"],
                ],
                10 => [
                    ["Malvin", "Teréz"],
                    ["Petra", "Örs"],
                    ["Helga", "Évald"],
                    ["Ferenc", "Hajnalka"],
                    ["Aurél", "Placid", "Attila", "Rella"],
                    ["Brúnó", "Renáta", "Renátó"],
                    ["Amália", "Bekény"],
                    ["Koppány", "Benedikta"],
                    ["Dénes", "János"],
                    ["Gedeon", "Ferenc", "Bendegúz"],
                    ["Brigitta", "Placida", "Etel", "Gitta"],
                    ["Miksa", "Rezső", "Edvin"],
                    ["Kálmán", "Ede", "Edvárd"],
                    ["Helén", "Kaldixtusz"],
                    ["Teréz", "Aranka"],
                    ["Gál", "Margit", "Hedvig"],
                    ["Hedvig", "Ignác", "Rudolf"],
                    ["Lukács", "Jusztusz"],
                    ["Nándor", "János", "Pál"],
                    ["Vendel", "Irén", "Kleopátra"],
                    ["Orsolya", "Zsolt"],
                    ["Előd", "Szalóme", "Kordélia"],
                    ["Gyöngyvér", "János", "Gyöngyi"],
                    ["Salamon", "Antal"],
                    ["Blanka", "Bianka", "Mór"],
                    ["Dömötör", "Armand", "Örs"],
                    ["Szabina", "Antonietta"],
                    ["Simon", "Szimonetta", "Szimóna", "Júdás", "Tádé"],
                    ["Nárcisz", "Melinda", "Őzike"],
                    ["Alfonz", "Zenóbia"],
                    ["Farkas", "Rodrigó", "Wolfgang"],
                ],
                11 => [
                    ["Marianna"],
                    ["Achilles", "Bató"],
                    ["Győző", "Márton"],
                    ["Károly", "Karola"],
                    ["Imre", "Zakariás", "Tétény"],
                    ["Lénárd", "Krisztina"],
                    ["Csenger", "Rezső", "Ernő", "Florentin"],
                    ["Zsombor", "Kolos", "Gottfrid"],
                    ["Tivadar"],
                    ["Réka", "András", "Leó"],
                    ["Márton", "Atád", "Tódor"],
                    ["Jónás", "Renátó", "Jozafát"],
                    ["Szilvia", "Szaniszló"],
                    ["Aliz", "Vanda", "Huba", "Klementina"],
                    ["Albert", "Lipót"],
                    ["Ödön", "Margit"],
                    ["Hortenzia", "Gergő", "Dénes"],
                    ["Jenő"],
                    ["Erzsébet", "Zsóka"],
                    ["Jolán", "Zsolt", "Ödön", "Bódog"],
                    ["Olivér"],
                    ["Cecília", "Filemon"],
                    ["Kelemen", "Klementina", "Kolumbán"],
                    ["Emma", "Flóra", "Virág"],
                    ["Katalin", "Liza", "Katinka"],
                    ["Virág", "Szvetlana", "Konrád", "Viktória", "Milos"],
                    ["Virgil", "Virgínia"],
                    ["Stefánia", "Jakab"],
                    ["Taksony", "Ilma", "Filoména"],
                    ["András", "Andor", "Andrea"],
                ],
                12 => [
                    ["Elza", "Natália", "Blanka", "Bonita"],
                    ["Melinda", "Vivien", "Aranka"],
                    ["Ferenc", "Olívia"],
                    ["Borbála", "Barbara", "János"],
                    ["Vilma", "Ünige", "Csaba"],
                    ["Miklós", "Csinszka", "Gyopár", "Gyopárka"],
                    ["Ambrus", "Ambrózia"],
                    ["Mária", "Emőke"],
                    ["Natália", "Valéria", "Filótea"],
                    ["Judit", "Loretta", "Eulália"],
                    ["Árpád", "Árpádina", "Damazusz"],
                    ["Gabriella", "Johanna", "Franciska"],
                    ["Luca", "Otília", "Lúcia", "Éda", "Tilia"],
                    ["Szilárda", "Szilárd", "János"],
                    ["Valér", "Detre"],
                    ["Etelka", "Aletta", "Adelaida"],
                    ["Lázár", "Olimpia"],
                    ["Auguszta", "Gracián"],
                    ["Viola", "Anasztáz"],
                    ["Teofil", "Liberátusz"],
                    ["Tamás", "Péter"],
                    ["Zénó", "Flórián"],
                    ["Viktória", "János"],
                    ["Ádám", "Éva", "Adél"],
                    ["Eugénia", "Anasztázia"],
                    ["István"],
                    ["János", "Teodor"],
                    ["Kamilla", "Apor"],
                    ["Tamás", "Tamara"],
                    ["Dávid", "Hunor", "Libériusz"],
                    ["Szilveszter", "Donáta"],
                ],
            ],
            'pl_PL' => [
                1 => [
                    ["Mieczysław", "Mieczysława", "Mieszko"],
                    ["Abel", "Achacy", "Achacjusz", "Aspazja", "Bazyli", "Izydor", "Jakobina", "Jakubina", "Makary", "Narcyz", "Stefania", "Strzeżysław", "Sylwester", "Sylwestra", "Telesfor", "Telesfora"],
                    ["Danuta", "Piotr", "Genowefa"],
                    ["Angelika", "Aniela", "Dobromir", "Eugeniusz", "Grzegorz", "Izabela"],
                    ["Edward", "Emilian", "Hania", "Szymon"],
                    ["Andrzej", "Bolemir", "Kacper", "Kasper"],
                    ["Julian", "Lucjan", "Walenty"],
                    ["Mścisław", "Seweryn"],
                    ["Antoni", "Borzymir", "Julian", "Julianna"],
                    ["Dobrosław", "Jan", "Paweł"],
                    ["Feliks", "Krzesimir", "Matylda"],
                    ["Antoni", "Arkadiusz", "Benedykt", "Czesław", "Czesława", "Ernest"],
                    ["Bogumił", "Bogusława", "Weronika"],
                    ["Feliks", "Radogost", "Felkis"],
                    ["Aleksander", "Dąbrówka", "Dobrawa", "Domasław", "Paweł"],
                    ["Marcel", "Włodzimierz", "Kevin"],
                    ["Antoni", "Jan", "Rościsław"],
                    ["Bogumił", "Jaropełk", "Krystyna", "Małgorzata", "Piotr"],
                    ["Andrzej", "Bernard", "Erwin", "Henryk", "Mariusz", "Marta", "Racimir", "Sara"],
                    ["Dobiegniew", "Fabian", "Sebastian"],
                    ["Agnieszka", "Jarosław", "Jarosława", "Marcela"],
                    ["Anastazy", "Dobromysł", "Dorian", "Marta", "Wincenty"],
                    ["Jan", "Maria"],
                    ["Felicja", "Mirogniew", "Rafaela", "Rafał", "Tymoteusz"],
                    ["Miłosz", "Miłowan", "Miłowit", "Paweł", "Tatiana", "Maleszka"],
                    ["Paula", "Paulina", "Wanda"],
                    ["Angelika", "Ilona", "Julian"],
                    ["Agnieszka", "Augustyn", "Julian", "Karol", "Piotr", "Radomir"],
                    ["Hanna", "Walerian", "Zdzisław"],
                    ["Feliks", "Gerard", "Maciej", "Marcin", "Martyna", "Sebastian"],
                    ["Euzebiusz", "Jan", "Piotr"],
                ],
                2 => [
                    ["Dobrochna", "Iga", "Ignacy", "Paweł", "Siemirad", "Żegota"],
                    ["Joanna", "Korneliusz", "Maria", "Miłosława", "Rory"],
                    ["Błażej", "Maksym", "Oskar", "Stefan", "Telimena"],
                    ["Andrzej", "Gilbert", "Jan", "Joanna", "Józef", "Weronika", "Witosława"],
                    ["Aga", "Agata", "Jakub", "Jan", "Paweł", "Piotr"],
                    ["Antoni", "Bogdan", "Bohdan", "Dorota", "Ksenia", "Szymon"],
                    ["Alfons", "Parteniusz", "Partenia", "Romeusz", "Romuald", "Rozalia", "Ryszard", "Sulisław"],
                    ["Gniewomir", "Jan", "Paweł", "Piotr", "Sebastian"],
                    ["Bernard", "Eryk", "Eryka"],
                    ["Gabriel", "Jacek", "Elwira"],
                    ["Lucjan", "Maria", "Olgierd", "Świętomira"],
                    ["Julian", "Laurenty", "Nora"],
                    ["Grzegorz", "Jordan", "Katarzyna", "Toligniew"],
                    ["Dobiesława", "Józef", "Konrad", "Krystyna", "Lilian", "Liliana", "Mikołaj", "Niemir", "Niemira", "Zenon", "Cyryl"],
                    ["Georgina", "Jordan", "Jowita", "Józef", "Klaudiusz"],
                    ["Bernard", "Dan", "Danuta", "Julianna"],
                    ["Donata", "Franciszek", "Julian", "Konstanty", "Łukasz", "Niegomir", "Zbigniew", "Zbyszko"],
                    ["Albert", "Alberta", "Krystiana", "Więcesława", "Zuzanna"],
                    ["Arnold", "Henryk", "Konrad"],
                    ["Leon", "Ludmiła", "Ludomiła"],
                    ["Eleonora", "Feliks", "Teodor"],
                    ["Marta", "Małgorzata", "Piotr", "Wiktor"],
                    ["Bądzimir", "Damian", "Piotr", "Roma", "Seweryn"],
                    ["Bogurad", "Bogusz", "Boguta", "Maciej", "Piotr"],
                    ["Bolebor", "Cezary", "Maciej", "Małgorzata"],
                    ["Aleksander", "Bogumił", "Cezariusz", "Mirosław", "Ewelina"],
                    ["Aleksander", "Anastazja", "Gabriel", "Gabriela", "Sierosława"],
                    ["Józef", "Roman", "Lech"],
                    ["Dobronieg", "Roman"],
                ],
                3 => [
                    ["Albin", "Antoni", "Antonina", "Amelia", "Feliks", "Herakles", "Joanna", "Józef", "Piotr"],
                    ["Franciszek", "Helena", "Henryk", "Krzysztof", "Michał", "Paweł", "Piotr", "Radosław"],
                    ["Hieronim", "Maryna"],
                    ["Adrian", "Adrianna", "Arkadiusz", "Eugeniusz", "Kazimierz", "Lucja"],
                    ["Adrian", "Adrianna", "Fryderyk", "Jan", "Wacław", "Wacława"],
                    ["Eugenia", "Jordan", "Klaudian", "Róża", "Wiktor", "Wojsław"],
                    ["Felicja", "Paweł", "Tomasz"],
                    ["Beata", "Jan", "Julian", "Miligost", "Miłogost", "Stefan"],
                    ["Dominik", "Franciszka", "Katarzyna"],
                    ["Aleksander", "Borzysław", "Cyprian"],
                    ["Benedykt", "Drogosława", "Edwin", "Konstantyn", "Rozyna"],
                    ["Bernard", "Blizbor", "Grzegorz", "Józefina"],
                    ["Bożena", "Ernest", "Kasjan", "Krystyna", "Marek"],
                    ["Bożeciecha", "Jakub", "Leon", "Matylda", "Michał"],
                    ["Gościmir", "Klemens", "Krzysztof", "Ludwika"],
                    ["Henryka", "Herbert", "Izabela"],
                    ["Gertruda", "Jan", "Patryk", "Zbigniew", "Zbyszko"],
                    ["Aleksander", "Boguchwał", "Cyryl", "Edward"],
                    ["Bogdan", "Józef"],
                    ["Aleksander", "Aleksandra", "Bogusław", "Klaudia"],
                    ["Benedykt", "Lubomira", "Mikołaj"],
                    ["Bogusław", "Katarzyna", "Kazimierz", "Paweł"],
                    ["Feliks", "Katarzyna", "Piotr"],
                    ["Gabriel", "Marek", "Szymon"],
                    ["Ireneusz", "Łucja", "Lucja", "Lutomysł", "Maria", "Wieńczysław"],
                    ["Emanuel", "Feliks", "Manuela", "Teodor"],
                    ["Benedykt", "Ernest", "Jan", "Lidia", "Rupert"],
                    ["Aniela", "Antoni", "Jan"],
                    ["Cyryl"],
                    ["Amelia", "Aniela", "Częstobor", "Jan"],
                    ["Beniamin", "Dobromira", "Kornelia"],
                ],
                4 => [
                    ["Grażyna", "Katarzyna", "Teodora", "Tolisław", "Zbigniew", "Zbyszko"],
                    ["Franciszek", "Sądomir", "Władysław", "Władysława"],
                    ["Antoni", "Cieszygor", "Jakub", "Ryszard"],
                    ["Benedykt", "Izydor", "Wacław", "Wacława"],
                    ["Borzywoj", "Irena", "Wincenty", "Jam"],
                    ["Ada", "Adam", "Ireneusz", "Katarzyna", "Świętobor"],
                    ["Donata", "Przecław"],
                    ["Cezary", "Radosław", "Sieciesława"],
                    ["Dobrosława", "Dymitr", "Maja"],
                    ["Antoni", "Daniel", "Henryk", "Małgorzata", "Michał"],
                    ["Filip", "Jaromir", "Leon", "Marek"],
                    ["Andrzej", "Iwan", "Juliusz", "Siemiodrog", "Wiktor", "Zenon"],
                    ["Jan", "Justyn", "Małgorzata", "Marcin", "Przemysł", "Przemysław"],
                    ["Julianna", "Justyn", "Maria", "Myślimir"],
                    ["Anastazja", "Leonid", "Wacław", "Wacława"],
                    ["Erwin", "Julia", "Ksenia", "Nikita", "Nosisław"],
                    ["Jakub", "Józef", "Klara", "Radociech", "Robert", "Rudolf", "Stefan"],
                    ["Bogusław", "Bogusława", "Gościsław"],
                    ["Cieszyrad", "Czechasz", "Czesław", "Leon", "Tymon", "Werner", "Włodzimierz"],
                    ["Agnieszka", "Czechoń", "Czesław", "Nawoj", "Szymon", "Teodor"],
                    ["Bartosz", "Drogomił", "Feliks", "Konrad"],
                    ["Kajus", "Kaja", "Łukasz", "Teodor"],
                    ["Gerard", "Helena", "Jerzy", "Wojciech"],
                    ["Aleksander", "Erwin", "Grzegorz"],
                    ["Jarosław", "Marek"],
                    ["Maria", "Marzena", "Spycimir"],
                    ["Andrzej", "Bożebor", "Martyn", "Piotr", "Zyta"],
                    ["Maria", "Paweł"],
                    ["Angelina", "Augustyn", "Bogusław", "Piotr", "Robert"],
                    ["Bartłomiej", "Jakub", "Katarzyna", "Marian"],
                ],
                5 => [
                    ["Aniela", "Filip", "Jakub", "Józef", "Lubomir", "Maja"],
                    ["Walter", "Witomir", "Zygmunt", "Wouter"],
                    ["Aleksander", "Antonina", "Maria", "Mariola", "Świętosława"],
                    ["Grzegorz", "Michał", "Monika"],
                    ["Irena", "Teodor", "Waldemar"],
                    ["Gościwit", "Jan", "Judyta"],
                    ["Benedykt", "Bogumir", "Ludmiła", "Ludomiła"],
                    ["Marek", "Michał", "Piotr", "Stanisław"],
                    ["Bożydar", "Grzegorz", "Karolina", "Mikołaj"],
                    ["Częstomir", "Jan"],
                    ["Filip", "Franciszek", "Iga", "Ignacy", "Lew", "Lutogniew", "Mira", "Żegota"],
                    ["Dominik", "Jan", "Joanna", "Wszemił", "Pankracy"],
                    ["Andrzej", "Ciechosław", "Gloria", "Magdalena", "Piotr", "Robert"],
                    ["Dobiesław", "Wiktor", "Maciej"],
                    ["Jan", "Zofia"],
                    ["Andrzej", "Jędrzej", "Szymon", "Wieńczysław"],
                    ["Bruno", "Sławomir", "Weronika", "Wiktor"],
                    ["Aleksander", "Aleksandra", "Alicja", "Edwin", "Eryk", "Eryka", "Feliks", "Irena", "Myślibor"],
                    ["Augustyn", "Celestyn", "Mikołaj", "Pękosław", "Piotr", "Timur"],
                    ["Bronimir", "Teodor", "Wiktoria"],
                    ["Donata", "Jan", "Tymoteusz", "Wiktor"],
                    ["Emil", "Helena", "Jan", "Julia", "Ryta", "Wiesław", "Wiesława", "Wisława"],
                    ["Budziwoj", "Emilia", "Iwona", "Jan", "Michał"],
                    ["Cieszysława", "Jan", "Joanna", "Maria", "Zula", "Zuzanna"],
                    ["Grzegorz", "Imisława", "Maria Magdalena"],
                    ["Filip", "Marianna", "Paulina", "Ewelina", "Więcemił"],
                    ["Jan", "Juliusz", "Lucjan", "Magdalena", "Radowit"],
                    ["Augustyn", "Jaromir", "Wiktor", "Wrocimir"],
                    ["Bogusława", "Maksymilian", "Maria", "Magdalena", "Teodor", "Urszula"],
                    ["Feliks", "Joanna"],
                    ["Aniela", "Bożysława", "Teodor"],
                ],
                6 => [
                    ["Bernard", "Jakub", "Konrad", "Magdalena", "Nikodem", "Symeon", "Świętopełk"],
                    ["Eugeniusz", "Maria", "Marianna", "Mikołaj", "Piotr", "Racisław"],
                    ["Konstantyn", "Leszek", "Paula", "Tamara"],
                    ["Franciszek", "Gościmił", "Karol"],
                    ["Dobrociech", "Dobromir", "Dobrymir"],
                    ["Dominika", "Norbert", "Paulina", "Więcerad"],
                    ["Antoni", "Ciechomir", "Jarosław", "Paweł", "Robert", "Wiesław", "Wisław"],
                    ["Maksym", "Seweryn", "Wyszesław"],
                    ["Felicjan"],
                    ["Bogumił", "Edgar", "Małgorzata"],
                    ["Feliks", "Radomił"],
                    ["Antonina", "Jan", "Leon", "Wyszemir"],
                    ["Antoni", "Chociemir", "Lucjan", "Maria Magdalena", "Tobiasz"],
                    ["Eliza", "Justyn", "Justyna", "Ninogniew"],
                    ["Angelina", "Jolanta", "Witold", "Witołd", "Witolda", "Witosław"],
                    ["Alina", "Aneta", "Budzimir", "Jan", "Justyna"],
                    ["Agnieszka", "Drogomysł", "Franciszek", "Laura", "Marcjan", "Radomił"],
                    ["Elżbieta", "Marek", "Marina", "Paula"],
                    ["Julianna"],
                    ["Bogna", "Bogumiła", "Bożena", "Franciszek", "Michał", "Rafaela", "Rafał"],
                    ["Alicja", "Domamir", "Marta", "Teodor"],
                    ["Broniwoj", "Paulina"],
                    ["Józef", "Piotr", "Wanda", "Zenon"],
                    ["Dan", "Danisz", "Danuta", "Emilia", "Jan"],
                    ["Lucja", "Łucja", "Tolisława"],
                    ["Jan", "Paweł"],
                    ["Maria Magdalena", "Władysław", "Władysława"],
                    ["Ireneusz", "Józef", "Leon", "Paweł"],
                    ["Dalebor", "Paweł", "Piotr"],
                    ["Ciechosława", "Emilia", "Lucyna"],
                ],
                7 => [
                    ["Halina", "Marian"],
                    ["Maria", "Piotr", "Jagoda"],
                    ["Jacek", "Leon", "Miłosław"],
                    ["Elżbieta", "Józef", "Julian", "Teodor", "Wielisław"],
                    ["Antoni", "Bartłomiej", "Jakub", "Karolina", "Michał"],
                    ["Chociebor", "Dominik", "Dominika", "Łucja", "Lucja", "Niegosław"],
                    ["Antoni", "Kira", "Piotr"],
                    ["Adrian", "Adrianna", "Chwalimir", "Edgar", "Elżbieta", "Eugeniusz"],
                    ["Łucja", "Lucja", "Mikołaj", "Weronika", "Zenon"],
                    ["Aleksander", "Amelia", "Aniela", "Filip"],
                    ["Cyprian", "Kalina", "Olga"],
                    ["Andrzej", "Euzebiusz", "Feliks", "Henryk", "Paweł", "Piotr", "Tolimir", "Weronika"],
                    ["Ernest", "Eugeniusz", "Jakub", "Justyna", "Małgorzata", "Radomiła", "Sara"],
                    ["Damian", "Dobrogost", "Franciszek", "Izabela", "Marcelina"],
                    ["Daniel", "Dawid", "Henryk", "Iga", "Ignacy", "Lubomysł", "Niecisław", "Włodzimierz", "Żegota"],
                    ["Andrzej", "Maria Magdalena", "Marika", "Stefan"],
                    ["Aleksander", "Andrzej", "Bogdan", "Marcelina", "Maria Magdalena"],
                    ["Erwin", "Kamil", "Karolina", "Robert", "Szymon", "Unisław"],
                    ["Lutobor", "Wincenty"],
                    ["Czechoń", "Czesław", "Małgorzata", "Paweł"],
                    ["Andrzej", "Daniel", "Paulina", "Stojsław", "Wiktor"],
                    ["Bolesława", "Bolisława", "Maria Magdalena", "Milenia", "Więcemiła"],
                    ["Bogna", "Żelisław"],
                    ["Antoni", "Kinga", "Krystyna", "Olga", "Wojciecha"],
                    ["Jakub", "Krzysztof", "Sławosz", "Walentyna"],
                    ["Anna", "Baldev", "Grażyna", "Mirosława"],
                    ["Julia", "Marta", "Natalia"],
                    ["Marcela", "Świętomir", "Wiktor"],
                    ["Konstantyn", "Maria", "Marta"],
                    ["Julia", "Julita", "Ludmiła", "Maryna"],
                    ["Emilian", "Helena", "Iga", "Ignacy", "Ludomir"],
                ],
                8 => [
                    ["Konrad", "Piotr"],
                    ["Borzysława", "Karina", "Maria", "Stefan"],
                    ["Augusta", "Lidia", "Nikodem", "Szczepan"],
                    ["Dominik", "Maria", "Mironieg"],
                    ["Emil", "Maria", "Stanisława"],
                    ["Jakub", "Sława", "Stefan", "Wincenty"],
                    ["Anna", "Dobiemir", "Donata", "Dorota", "Kajetan"],
                    ["Cyprian", "Cyryl", "Emil", "Emilian", "Emiliusz"],
                    ["Jan", "Klarysa", "Miłorad", "Roman"],
                    ["Bogdan", "Borys"],
                    ["Aleksander", "Włodzimierz", "Włodziwoj", "Zula", "Zuzanna"],
                    ["Klara", "Lech", "Piotr"],
                    ["Diana", "Helena", "Jan", "Kasjan", "Radomiła", "Wojbor"],
                    ["Dobrowoj", "Euzebiusz"],
                    ["Maria", "Stefan"],
                    ["Domarad", "Domarat", "Joachim"],
                    ["Anastazja", "Angelika", "Anita", "Eliza", "Jacek", "Jaczewoj", "Joanna", "Julianna", "Miron", "Żanna"],
                    ["Bogusława", "Bronisław", "Bronisz", "Helena", "Ilona", "Klara"],
                    ["Bolesław", "Emilia", "Jan", "Julian", "Juliusz", "Piotr"],
                    ["Jan", "Samuel", "Samuela", "Sieciech", "Sobiesław", "Świeciech"],
                    ["Emilian", "Filipina", "Franciszek", "Joanna", "Kazimiera", "Męcimir"],
                    ["Cezary", "Dalegor", "Maria", "Namysław", "Tymoteusz", "Zygfryd"],
                    ["Filip", "Laurenty"],
                    ["Bartłomiej", "Cieszymir", "Jerzy", "Joanna", "Malina", "Michalina"],
                    ["Grzegorz", "Luiza", "Michał", "Sieciesław"],
                    ["Dobroniega", "Joanna", "Konstanty", "Maksym", "Maria"],
                    ["Cezary", "Józef", "Monika", "Małgorzata", "Teodor"],
                    ["Adelina", "Aleksander", "Aleksy", "Augustyn", "Patrycja", "Sobiesław", "Stronisław"],
                    ["Gita", "Jan", "Racibor", "Sabina"],
                    ["Częstowoj", "Miron", "Rebeka", "Róża", "Szczęsna", "Szczęsny"],
                    ["Bohdan", "Paulina", "Rajmund", "Świętosław"],
                ],
                9 => [
                    ["Bronisław", "Bronisława", "Bronisz"],
                    ["Bohdan", "Czesław", "Eliza", "Henryk", "Julian", "Stefan", "Tobiasz", "Witomysł"],
                    ["Antoni", "Bartłomiej", "Bronisław", "Bronisz", "Izabela", "Jan", "Joachim", "Mojmir", "Szymon", "Wincenty", "Zenon"],
                    ["Ida", "Lilianna", "Rościgniew", "Róża", "Rozalia"],
                    ["Dorota", "Justyna", "Stronisława", "Wawrzyniec"],
                    ["Albin", "Beata", "Eugenia", "Eugeniusz", "Michał", "Uniewit"],
                    ["Domasława", "Domisława", "Marek", "Regina", "Rena", "Ryszard"],
                    ["Adrian", "Adrianna", "Maria", "Radosław", "Radosława", "Klementyna"],
                    ["Augustyna", "Aureliusz", "Piotr", "Ścibor", "Ścibora", "Sergiusz", "Sobiesąd"],
                    ["Aldona", "Łukasz", "Mikołaj", "Mścibor"],
                    ["Feliks", "Jacek", "Jan", "Naczesław"],
                    ["Amadeusz", "Maria", "Piotr", "Sylwin"],
                    ["Aleksander", "Eugenia", "Filip", "Lubor", "Morzysław", "Szeliga"],
                    ["Bernard", "Cyprian", "Roksana", "Siemomysł", "Szymon"],
                    ["Maria", "Nikodem"],
                    ["Cyprian", "Edyta", "Eugenia", "Franciszek", "Kamila", "Kornel", "Lucja", "Łucja", "Wiktor"],
                    ["Drogosław", "Franciszek", "Justyn", "Justyna", "Teodora"],
                    ["Dobrowit", "Irena", "Józef", "Stefania"],
                    ["Konstancja", "Teodor", "Więcemir"],
                    ["Agnieszka", "Barbara", "Dionizy", "Eustachiusz", "Eustachy", "Fausta", "Faustyna", "Filipina", "Irena", "Klemens", "Mieczysława", "Miłowuj", "Oleg", "Perpetua", "Protazy"],
                    ["Bożeciech", "Bożydar", "Jonasz", "Laurenty", "Mateusz", "Mira"],
                    ["Joachim", "Maurycy", "Prosimir", "Scott", "Tomasz"],
                    ["Boguchwała", "Bogusław", "Elżbieta", "Krzysztof", "Libert", "Litoriusz", "Liwiusz", "Piotr", "Tekla", "Zachariusz"],
                    ["Gerard", "Maria", "Teodor", "Tomir", "Uniegost"],
                    ["Aurelia", "Franciszek", "Kamil", "Ładysław", "Piotr", "Świętopełk", "Wincenty", "Władysław", "Władysława"],
                    ["Cyprian", "Euzebiusz", "Justyna", "Łękomir"],
                    ["Amadeusz", "Damian"],
                    ["Jan", "Luba", "Lubosza", "Marek", "Nikita", "Sylwin", "Wacław", "Wacława", "Więcesław"],
                    ["Michał", "Rafał", "Gabriel"],
                    ["Grzegorz", "Hieronim", "Honoriusz", "Imisław", "Rachela", "Wera", "Wiera", "Wiktor", "Zofia"],
                ],
                10 => [
                    ["Danuta", "Remigiusz", "Cieszysław", "Dan", "Danisz", "Danuta", "Igor", "Jan", "Remigiusz"],
                    ["Stanimir", "Teofil"],
                    ["Gerard", "Józefa", "Sierosław", "Teresa"],
                    ["Edwin", "Franciszek", "Konrad", "Rozalia"],
                    ["Częstogniew", "Donata", "Igor", "Justyn", "Konstancjusz"],
                    ["Artur", "Bronisław", "Bronisz", "Emil", "Roman"],
                    ["Justyna", "Marek", "Maria", "Rościsława", "Stefan"],
                    ["Bryda", "Brygida", "Laurencja", "Marcin", "Wojsława"],
                    ["Bogdan", "Jan", "Ludwik"],
                    ["Franciszek", "Lutomir", "Tomił"],
                    ["Aldona", "Dobromiła", "Emil", "Emilian", "Emiliusz", "Maria", "Marian"],
                    ["Maksymilian", "Witold"],
                    ["Daniel", "Edward", "Mikołaj", "Siemisław"],
                    ["Alan", "Bernard", "Dominik"],
                    ["Jadwiga", "Teresa"],
                    ["Aurelia", "Gerard", "Grzegorz"],
                    ["Lucyna", "Małgorzata", "Marian", "Wiktor"],
                    ["Julian", "Łukasz"],
                    ["Ferdynand", "Piotr", "Siemowit", "Skarbimir", "Ziemowit"],
                    ["Irena", "Urszula"],
                    ["Bernard", "Celina", "Dobromił", "Elżbieta"],
                    ["Filip", "Halka"],
                    ["Iga", "Ignacy", "Jan", "Marlena", "Roman", "Seweryn", "Teodor", "Włościsław", "Żegota"],
                    ["Antoni", "Boleczest", "Filip", "Marcin", "Rafaela", "Rafał"],
                    ["Daria", "Kryspin", "Sambor", "Taras"],
                    ["Dymitriusz", "Łucjan", "Lucyna", "Ludmiła", "Lutosław"],
                    ["Iwona", "Sabina", "Wincenty"],
                    ["Szymon", "Tadeusz", "Wszeciech"],
                    ["Euzebia", "Franciszek", "Lubogost", "Teodor", "Wioletta"],
                    ["Edmund", "Klaudiusz", "Przemysław", "Sądosław"],
                    ["Antoni", "Antonina", "Godzimir", "Lucylla", "Łukasz", "Dezemir"],
                ],
                11 => [
                    ["Andrzej", "Seweryn", "Warcisław", "Wiktoryna"],
                    ["Bohdana", "Bożydar", "Małgorzata", "Stojmir", "Tobiasz"],
                    ["Bogumił", "Cezary", "Chwalisław", "Hubert", "Sylwia"],
                    ["Mściwój", "Olgierd", "Karol"],
                    ["Dalemir", "Elżbieta", "Florian", "Sławomir"],
                    ["Feliks", "Leonard", "Trzebowit", "Ziemowit"],
                    ["Antoni", "Florentyn", "Przemił"],
                    ["Dymitr", "Klaudiusz", "Seweryn", "Wiktor"],
                    ["Bogudar", "Genowefa", "Teodor", "Ursyn"],
                    ["Andrzej", "Lena", "Leon", "Ludomir", "Stefan"],
                    ["Anastazja", "Bartłomiej", "Maciej", "Marcin", "Spycisław", "Teodor"],
                    ["Cibor", "Czcibor", "Jonasz", "Krystyn", "Marcin", "Renata", "Witold"],
                    ["Arkadiusz", "Eugeniusz", "Jan", "Mikołaj", "Stanisław"],
                    ["Aga", "Agata", "Damian", "Elżbieta", "Emil", "Emiliusz", "Józef", "Judyta", "Ścibor", "Ścibora", "Wszerad"],
                    ["Albert", "Alfons", "Artur", "Gurias", "Idalia", "Józef", "Leopold", "Leopoldyna", "Przybygniew", "Roger"],
                    ["Edmund", "Marek", "Maria", "Niedamir", "Otomar", "Paweł", "Piotr"],
                    ["Grzegorz"],
                    ["Aniela", "Cieszymysł", "Klaudyna", "Roman", "Tomasz"],
                    ["Elżbieta", "Mironiega", "Paweł", "Seweryn"],
                    ["Edmund", "Feliks", "Sędzimir"],
                    ["Janusz", "Konrad", "Maria", "Piotr", "Regina", "Rena", "Twardosław", "Wiesław"],
                    ["Cecylia", "Marek", "Wszemiła"],
                    ["Adela", "Klemens", "Przedwoj"],
                    ["Dobrosław", "Emilia", "Emma", "Franciszek", "Gerard", "Jan", "Pęcisław"],
                    ["Katarzyna", "Tęgomir"],
                    ["Dobiemiest", "Jan", "Konrad", "Lechosław", "Lechosława", "Leonard", "Sylwester"],
                    ["Dominik", "Maksymilian", "Stojgniew", "Walery"],
                    ["Gościrad", "Grzegorz", "Jakub", "Lesław", "Lesława", "Zdzisław"],
                    ["Błażej", "Bolemysł", "Fryderyk", "Przemysł"],
                    ["Andrzej", "Justyna", "Konstanty"],
                ],
                12 => [
                    ["Blanka", "Długosz", "Edmund", "Iwa", "Natalia", "Sobiesława"],
                    ["Aurelia", "Balbina", "Bibiana", "Budzisław", "Budzisława", "Ludwina", "Paulina", "Sulisław", "Sylweriusz", "Sylwery", "Wiktoryn", "Zbylut"],
                    ["Franciszek", "Kasjan", "Lucjusz", "Unimir"],
                    ["Barbara", "Hieronim", "Krystian", "Piotr"],
                    ["Gerald", "Krystyna", "Pęcisława"],
                    ["Emilian", "Jarogniew", "Mikołaj"],
                    ["Marcin", "Ninomysł"],
                    ["Boguwola", "Maria", "Światozar"],
                    ["Joachim", "Wielisława", "Wiesław"],
                    ["Andrzej", "Daniel", "Judyta", "Julia", "Maria"],
                    ["Daniela", "Julia", "Stefan", "Waldemar", "Wojmir"],
                    ["Aleksander", "Dagmara"],
                    ["Lucja", "Łucja", "Otylia"],
                    ["Alfred", "Izydor", "Sławobor"],
                    ["Celina", "Iga", "Ignacy", "Krystiana", "Nina", "Wolimir", "Żegota"],
                    ["Alina", "Zdzisława"],
                    ["Florian", "Jolanta", "Żyrosław"],
                    ["Bogusław", "Gracjan", "Laurencja", "Wszemir"],
                    ["Beniamin", "Dariusz", "Gabriela", "Mścigniew", "Tymoteusz"],
                    ["Bogumiła", "Dominik"],
                    ["Tomasz", "Tomisław"],
                    ["Beata", "Drogomir", "Franciszka", "Zenon"],
                    ["Sławomir", "Sławomira", "Wiktoria"],
                    ["Adam", "Adamina", "Adela", "Ewa", "Ewelina", "Grzegorz"],
                    ["Anastazja", "Eugenia", "Piotr"],
                    ["Szczepan", "Wróciwoj"],
                    ["Cezary", "Jan", "Radomysł"],
                    ["Antoni", "Dobrowiest", "Emma"],
                    ["Domawit", "Dominik", "Gosław", "Jonatan", "Marcin", "Tomasz"],
                    ["Dawid", "Eugeniusz", "Katarzyna", "Uniedrog"],
                    ["Korneliusz", "Melania", "Sebastian", "Sylwester", "Tworzysław"],
                ],
            ],
        ];
    }

    public static function getLeapNames()
    {
        return [
            'hu_HU' => 'szökőnap',
            'pl_PL' => 'rok przestępny',
        ];
    }
}
